PALETTE = ["#8069EC", "#EA822C", "#2ECC71", "#D143A4", "#F1C40F", "#34495E", "#648FFF"]

STYLE = {
    "figure.figsize": (24, 20),
    "lines.linewidth": 8,
    "lines.markersize": 12,
    "lines.markeredgecolor": "#212121",
    "lines.markeredgewidth": 1,
    "text.color": "#212121",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.labelsize": 64,
    "axes.labelpad": 12,
    "axes.labelcolor": "#212121",
    "axes.labelweight": 600,
    "axes.linewidth": 6,
    "axes.edgecolor": "#212121",
    "xtick.bottom": True,
    "ytick.left": True,
    "xtick.major.pad": 12,
    "ytick.major.pad": 12,
    "xtick.labelsize": 56,
    "ytick.labelsize": 56,
    "xtick.color": "#212121",
    "ytick.color": "#212121",
    "xtick.major.size": 18,
    "ytick.major.size": 18,
    "xtick.major.width": 6,
    "ytick.major.width": 6,
    "xtick.minor.size": 6,
    "ytick.minor.size": 6,
    "xtick.minor.width": 2,
    "ytick.minor.width": 2,
    "legend.fontsize": 48,
    "legend.handletextpad": 0.4,
    "legend.labelspacing": 0.4,
    "legend.handlelength": 1,
    "grid.linewidth": 1,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.0,
}

STYLE_LARGE = {
    "figure.figsize": (24, 20),
    "lines.linewidth": 16,
    "lines.markersize": 24,
    "lines.markeredgecolor": "#212121",
    "lines.markeredgewidth": 2,
    "text.color": "#212121",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.labelsize": 96,
    "axes.labelpad": 18,
    "axes.labelcolor": "#212121",
    "axes.labelweight": 600,
    "axes.linewidth": 12,
    "axes.edgecolor": "#212121",
    "xtick.bottom": True,
    "ytick.left": True,
    "xtick.major.pad": 18,
    "ytick.major.pad": 18,
    "xtick.labelsize": 72,
    "ytick.labelsize": 72,
    "xtick.color": "#212121",
    "ytick.color": "#212121",
    "xtick.major.size": 36,
    "ytick.major.size": 36,
    "xtick.major.width": 12,
    "ytick.major.width": 12,
    "xtick.minor.size": 12,
    "ytick.minor.size": 12,
    "xtick.minor.width": 4,
    "ytick.minor.width": 4,
    "legend.fontsize": 64,
    "legend.handletextpad": 0.4,
    "legend.labelspacing": 0.4,
    "legend.handlelength": 1,
    "grid.linewidth": 2,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.0,
}
